version: '3.8'
services:

  db:
    image: postgres:13.7-alpine
    container_name: db_shareit
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  server:
    build: server
    container_name: shareit_server
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_DRIVER=org.postgresql.Driver
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - SERVER_PORT=9090

  gateway:
    build: gateway
    container_name: shareit_gateway
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      - GATEWAY_PORT=8080